version: "3.9"

services:
  # --- Хранилище исходных данных ---
  db:
    image: postgres:15-alpine
    container_name: lab2-pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: salesdb
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_pass_2024
    ports:
      - "5433:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/csv-import
      - pgdata:/var/lib/postgresql/data
    networks:
      - etl-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U etl_user -d salesdb"]
      interval: 5s
      retries: 10

  # --- Аналитическое хранилище ---
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.3
    container_name: lab2-ch
    restart: unless-stopped
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: analyst
      CLICKHOUSE_PASSWORD: ch_secure_456
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - chdata:/var/lib/clickhouse
    networks:
      - etl-network
    healthcheck:
      test: ["CMD", "clickhouse-client", "--user", "analyst", "--password", "ch_secure_456", "--query", "SELECT 1"]
      interval: 5s
      retries: 10

  # --- Apache Spark (standalone cluster) ---
  spark-master:
    image: bitnami/spark:3.5
    container_name: lab2-spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "9090:8080"
      - "7077:7077"
    networks:
      - etl-network

  spark-worker-1:
    image: bitnami/spark:3.5
    container_name: lab2-spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_CORES=2
    depends_on:
      - spark-master
    networks:
      - etl-network

  # --- Контейнер для запуска Spark-приложений ---
  runner:
    image: bitnami/spark:3.5
    container_name: lab2-runner
    environment:
      PG_JDBC_URL: "jdbc:postgresql://db:5432/salesdb"
      PG_USER: etl_user
      PG_PASSWORD: etl_pass_2024
      CH_JDBC_URL: "jdbc:ch://clickhouse-server:8123/analytics?compress=0"
      CH_USER: analyst
      CH_PASSWORD: ch_secure_456
    volumes:
      - ./spark-app:/opt/app
      - ./drivers:/opt/drivers
      - ./data:/csv-import
    depends_on:
      db:
        condition: service_healthy
      clickhouse-server:
        condition: service_healthy
      spark-master:
        condition: service_started
    networks:
      - etl-network
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  pgdata:
  chdata:

networks:
  etl-network:
    driver: bridge
